python /cephfs/shared/zlouyang/FP-Quant/model_quant.py \
  --model_name_or_path=/cephfs/shared/model/llama-3-8b-instruct \
  --dataset_name_or_path="${OUT_CALIB}/fineweb_calib_1024x2048_tokens.pt" \
  --num_sequences=1024 \
  --sequence_length=2048 \
  --dtype=auto \
  --format=mxfp \
  --w_bits=4 --a_bits=4 \
  --w_group_size=32 --a_group_size=32 \
  --w_granularity=group --a_granularity=group \
  --w_observer=mse \
  --gptq \
  --quantization_order=default \
  --transform_search \
  --transform_search_candidates identity hadamard dct dst gsr householder \
  --export_quantized_model=pseudoquant \
  --save_path=outputs/mxfp_gptq_mse_rotsearch_smoke \
  --cpu_offload_modules \
  --fuse_global_scale \
  --amp
